### PR TITLE
Convert uart jtag

### PR DESCRIPTION
**Pull request by andreasWallner**

### CODE REVIEW

**Comment by wifasoi** [comment]
Thanksto do some dirty work. I'll ask to drop the travis file, because the main repo now utilize github-actions for ci/cd.
We should also use the same Spinahdl version in the latest tag; Don't know if there is a way to give the Spinalhdl version to sbt via command line (need to read the sbt documentation first), but if so, it can be a solution.

**Comment by numero-744** [comment]
For `travis.sh` I have suggested deletion in: https://github.com/SpinalHDL/SpinalHDL/pull/908

For the SpinalHDL version I thought we could have it from [SpinalTemplateSbt](https://github.com/SpinalHDL/SpinalTemplateSbt) but you are right, it would put errors for un-released stuff.
I think in worst case we can `sed -i 's=expression=replacement=' build.sbt` to use `dev` branch?

**Comment by numero-744** [comment]
Reading the diff, I notice we re-create a Spinal environment. So we can simply do something like this? https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/About%20SpinalHDL/faq.html#how-to-use-an-unreleased-version-of-spinalhdl-but-committed-on-git

**Comment by andreasWallner** [comment]
> Thanksto do some dirty work. I'll ask to drop the travis file, because the main repo now utilize github-actions for ci/cd. We should also use the same Spinahdl version in the latest tag; Don't know if there is a way to give the Spinalhdl version to sbt via command line (need to read the sbt documentation first), but if so, it can be a solution.

Sure, hadn't followed the switch, I was actually a bit surprised as I had remembered that travis had stopped their free tier - but didn´t think more on that.

> Reading the diff, I notice we re-create a Spinal environment. So we can simply do something like this? https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/About%20SpinalHDL/faq.html#how-to-use-an-unreleased-version-of-spinalhdl-but-committed-on-git

I'm not sure I follow: in the repo here we have the basic sbt project that is needed for compilation - irrespective of which SpinalHDL version you are using. We'd need to do that in any case. In the long run it might make sense to refer to either a commit in the SpinalHDL repo or the dev branch (I normally prefer to refer to a specific commit/version, otherwise weird build errors can creep up in places someone didn't even change)

**Comment by andreasWallner** [comment]
> Thanksto do some dirty work. I'll ask to drop the travis file, because the main repo now utilize github-actions for ci/cd. We should also use the same Spinahdl version in the latest tag; Don't know if there is a way to give the Spinalhdl version to sbt via command line (need to read the sbt documentation first), but if so, it can be a solution.

As far as I know there is not - but in the end we can just use the current version, and once we add documentation for newer features increment that version. Should be good enough for 99% of the cases. (and in either case it's written down in some file)
I'd actually try to pull the one in from the sbt template, that is often notoriously outdated and add kind of a weird dependency if you ask me.

**Comment by numero-744** [comment]
> I'm not sure I follow: in the repo here we have the basic sbt project that is needed for compilation - irrespective of which SpinalHDL version you are using.

https://github.com/wifasoi/SpinalDoc-RTD/pull/2/files#diff-28eb49375883680a043eb988aa3ff609629f102066ac9d0898e82daf14af741fR5 Here the version of SpinalHDL is specified (I think Dolu [updates Sbt template](https://github.com/SpinalHDL/SpinalTemplateSbt/commit/8e8b22f6ec3191f0378aeced536ffcd14739dd33) on each release).

> We'd need to do that in any case.

Yes

> In the long run it might make sense to refer to either a commit in the SpinalHDL repo or the dev branch (I normally prefer to refer to a specific commit/version, otherwise weird build errors can creep up in places someone didn't even change)

I think dev should be good. In this case, I think that locking a specific commit might slow us:

* A dev creates a new feature / API
* The dev documents it for RTD and opens a PR with failing tests (okay for now)
* Code is merged into master
* The test of the added RTD examples still fails because it is locked to older, more stable version / commit.
* We have to re-commit to update Spinal version, to make the test pass.
* The version is changed in all PRs so it creates merge conflicts.

This added to what Readon [recently wrote](https://github.com/SpinalHDL/SpinalHDL/pull/901#issuecomment-1281074022) about how difficult it is to cross-PR, I wonder if we should eventually move RTD to a sub-directory of SpinalHDL… (I don't like this idea but maybe it should be discussed.)

> I'd actually try to pull the one in from the sbt template, that is often notoriously outdated and add kind of a weird dependency if you ask me.

I think Dolu [updates Sbt template](https://github.com/SpinalHDL/SpinalTemplateSbt/commit/8e8b22f6ec3191f0378aeced536ffcd14739dd33) on each release

**Comment by andreasWallner** [comment]
> https://github.com/wifasoi/SpinalDoc-RTD/pull/2/files#diff-28eb49375883680a043eb988aa3ff609629f102066ac9d0898e82daf14af741fR5 Here the version of SpinalHDL is specified (I think Dolu [updates Sbt template](https://github.com/SpinalHDL/SpinalTemplateSbt/commit/8e8b22f6ec3191f0378aeced536ffcd14739dd33) on each release).

I didn't get what you meant with "recreate" - but I guess now you meant that we could copy those files from the SpinalTemplateSbt in the build job? I'd actually not like to do that: it makes local building harder (yes you could provide a script for that, but getting that to work on multiple platforms is a chore). It can also create the problem that a version that you comitted yesterday where it compiled does not work anymore tomorrow (e.g. if a deprecated method was removed.

I think there is no real difference between pinning to dev or a specific commit on dev: if the code is already on dev when you write the documentation then you can just as well update to the hash of that specific version - it already exists and won't change. If it's an open PR then your new documentation won't build either way. The choice is basically between having to add a commit incrementing the hash vs. having to retrigger the job.

> I think Dolu [updates Sbt template](https://github.com/SpinalHDL/SpinalTemplateSbt/commit/8e8b22f6ec3191f0378aeced536ffcd14739dd33) on each release

Had a look, sorry to Dolu - it seems the latest version were always updated.

**Comment by numero-744** [comment]
Okay for me to not use a fresh sbt template in the CI, to make local testing easier as you mentioned.

There is something I don't understand:

> can also create the problem that a version that you comitted yesterday where it compiled does not work anymore tomorrow (e.g. if a deprecated method was removed.

The only thing which can change in the template is the Spinal version, isn't it?

Also, to me it is not an issue, it is a requirement. I want to run examples to check that documentation matches the code, to be sure users do not struggle with examples which contain errors. So if the code contains an example which cannot be run anymore, I think it is an issue, and it is a good thing to raise an error for it.

About dev vs commit hash, I think I prefer dev because it would make the RTD PR pass as soon as the code PR is merged, and not require the contributor to update the commit in a file.

Another solution could be to manage RTD in relation with SpinalHDL releases?

**Comment by andreasWallner** [comment]
> The only thing which can change in the template is the Spinal version, isn't it?

Yes, but changing the version of SpinalHDL you are building against can break "any" example.

> Also, to me it is not an issue, it is a requirement. I want to run examples to check that documentation matches the code, to be sure users do not struggle with examples which contain errors. So if the code contains an example which cannot be run anymore, I think it is an issue, and it is a good thing to raise an error for it.

Depends on your POV: if a certain version of RTD documents a specific version of SpinalHDL, then the examples should build against that version - even later.
But we can also decide that we do not care about older version of RTD examples still building - also a valid approach (since we can assume that it built correctly when it was merged), in that case just build with the current dev. And the documentation itself is still the same.

At least with the current setup this starts to make more sense to me (building against dev).
Might be a problem in the future if we ever start to include the code documentation via the sphinx scala domain (https://pythonhosted.org/sphinxcontrib-scaladomain/) - but we can cross that bridge when we get there.

I'll update the PR if we agree to build against the current SpinalHDL dev.

**Comment by andreasWallner** [comment]
Small update: I'm still struggling to add the dependency to the SpinalHDL repo directly in the build - I'll have to see if the sbt gitter/stackoverflow product any good idea as I'm out of them ;-)
In the end I'd really like to avoid saying: please clone SpinalHDL repo to folder x before you try to build the examples...
One other possibility that I thought about was to use a git submodule (since 1.8 a submodule can track a branch head), I'll try this this weekend.

**Comment by andreasWallner** [comment]
Another update: I had to do something productive again, so most of the intermediate examples are now converted (and fixed) as well....
Regarding the build setup: In Gitter we discussed to have the dev branch be published for each commit, this will allow us to use it here. I'd continue the conversion for now with the current build setup and swap that once we have that build published.

**Comment by wifasoi** [comment]
The workflow already trigger a rebuild on every commit form "master" and from "dev". But maybe I did not understand correctly your statement.

**Comment by numero-744** [comment]
@wifasoi I think it is more about deploying a "nightly" version that we could fetch to run tests in other repositories such as this one, not only building the Scala code to run tests.

**Comment by andreasWallner** [comment]
@numero-744 @wifasoi exactly that, the plan is to publish a snapshot release to maven/github for every push to `dev` - so we could here just build against that

**Comment by andreasWallner** [comment]
As discussed to today, moving the PR over to the SpinalDoc RTD repo

**Pull request closed without merging**
